"""Province mapping utilities for canonical 2-letter province codes."""

from __future__ import annotations

import re
from typing import Optional

# 110 canonical province-level sigle (Wikipedia + SU).
PROVINCE_SIGLAS_110 = [
    "AG",
    "AL",
    "AN",
    "AO",
    "AP",
    "AQ",
    "AR",
    "AT",
    "AV",
    "BA",
    "BG",
    "BI",
    "BL",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BZ",
    "CA",
    "CB",
    "CE",
    "CH",
    "CI",
    "CL",
    "CN",
    "CO",
    "CR",
    "CS",
    "CT",
    "CZ",
    "EN",
    "FC",
    "FE",
    "FG",
    "FI",
    "FM",
    "FR",
    "GE",
    "GO",
    "GR",
    "IM",
    "IS",
    "KR",
    "LC",
    "LE",
    "LI",
    "LO",
    "LT",
    "LU",
    "MB",
    "MC",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NA",
    "NO",
    "NU",
    "OG",
    "OR",
    "PA",
    "PC",
    "PD",
    "PE",
    "PG",
    "PI",
    "PN",
    "PO",
    "PR",
    "PT",
    "PU",
    "PV",
    "PZ",
    "RA",
    "RC",
    "RE",
    "RG",
    "RI",
    "RM",
    "RN",
    "RO",
    "SA",
    "SI",
    "SO",
    "SP",
    "SR",
    "SS",
    "SU",
    "SV",
    "TA",
    "TE",
    "TN",
    "TO",
    "TP",
    "TR",
    "TS",
    "TV",
    "UD",
    "VA",
    "VB",
    "VC",
    "VE",
    "VI",
    "VR",
    "VS",
    "VT",
    "VV",
]

# Province to region mapping (for geographic interpolation).
PROVINCE_TO_REGION = {
    "AG": "Sicilia",
    "AL": "Piemonte",
    "AN": "Marche",
    "AO": "Valle d'Aosta",
    "AP": "Marche",
    "AQ": "Abruzzo",
    "AR": "Toscana",
    "AT": "Piemonte",
    "AV": "Campania",
    "BA": "Puglia",
    "BG": "Lombardia",
    "BI": "Piemonte",
    "BL": "Veneto",
    "BN": "Campania",
    "BO": "Emilia-Romagna",
    "BR": "Puglia",
    "BS": "Lombardia",
    "BT": "Puglia",
    "BZ": "Trentino-Alto Adige",
    "CA": "Sardegna",
    "CB": "Molise",
    "CE": "Campania",
    "CH": "Abruzzo",
    "CI": "Sardegna",
    "CL": "Sicilia",
    "CN": "Piemonte",
    "CO": "Lombardia",
    "CR": "Lombardia",
    "CS": "Calabria",
    "CT": "Sicilia",
    "CZ": "Calabria",
    "EN": "Sicilia",
    "FC": "Emilia-Romagna",
    "FE": "Emilia-Romagna",
    "FG": "Puglia",
    "FI": "Toscana",
    "FM": "Marche",
    "FR": "Lazio",
    "GE": "Liguria",
    "GO": "Friuli-Venezia Giulia",
    "GR": "Toscana",
    "IM": "Liguria",
    "IS": "Molise",
    "KR": "Calabria",
    "LC": "Lombardia",
    "LE": "Puglia",
    "LI": "Toscana",
    "LO": "Lombardia",
    "LT": "Lazio",
    "LU": "Toscana",
    "MB": "Lombardia",
    "MC": "Marche",
    "ME": "Sicilia",
    "MI": "Lombardia",
    "MN": "Lombardia",
    "MO": "Emilia-Romagna",
    "MS": "Toscana",
    "MT": "Basilicata",
    "NA": "Campania",
    "NO": "Piemonte",
    "NU": "Sardegna",
    "OG": "Sardegna",
    "OR": "Sardegna",
    "PA": "Sicilia",
    "PC": "Emilia-Romagna",
    "PD": "Veneto",
    "PE": "Abruzzo",
    "PG": "Umbria",
    "PI": "Toscana",
    "PN": "Friuli-Venezia Giulia",
    "PO": "Toscana",
    "PR": "Emilia-Romagna",
    "PT": "Toscana",
    "PU": "Marche",
    "PV": "Lombardia",
    "PZ": "Basilicata",
    "RA": "Emilia-Romagna",
    "RC": "Calabria",
    "RE": "Emilia-Romagna",
    "RG": "Sicilia",
    "RI": "Lazio",
    "RM": "Lazio",
    "RN": "Emilia-Romagna",
    "RO": "Veneto",
    "SA": "Campania",
    "SI": "Toscana",
    "SO": "Lombardia",
    "SP": "Liguria",
    "SR": "Sicilia",
    "SS": "Sardegna",
    "SU": "Sardegna",
    "SV": "Liguria",
    "TA": "Puglia",
    "TE": "Abruzzo",
    "TN": "Trentino-Alto Adige",
    "TO": "Piemonte",
    "TP": "Sicilia",
    "TR": "Umbria",
    "TS": "Friuli-Venezia Giulia",
    "TV": "Veneto",
    "UD": "Friuli-Venezia Giulia",
    "VA": "Lombardia",
    "VB": "Piemonte",
    "VC": "Piemonte",
    "VE": "Veneto",
    "VI": "Veneto",
    "VR": "Veneto",
    "VS": "Sardegna",
    "VT": "Lazio",
    "VV": "Calabria",
}

# Italy's standard statistical macro-areas (ripartizioni geografiche), collapsed
# to the three groups the North--South debate uses: North (Nord-Ovest +
# Nord-Est), Centre (Centro), and South / Mezzogiorno (Sud + Isole). Used to
# read the distributional results in territorial terms (sera report).
REGION_TO_MACROAREA = {
    # North
    "Piemonte": "North",
    "Valle d'Aosta": "North",
    "Liguria": "North",
    "Lombardia": "North",
    "Trentino-Alto Adige": "North",
    "Veneto": "North",
    "Friuli-Venezia Giulia": "North",
    "Emilia-Romagna": "North",
    # Centre
    "Toscana": "Centre",
    "Umbria": "Centre",
    "Marche": "Centre",
    "Lazio": "Centre",
    # South / Mezzogiorno
    "Abruzzo": "South",
    "Molise": "South",
    "Campania": "South",
    "Puglia": "South",
    "Basilicata": "South",
    "Calabria": "South",
    "Sicilia": "South",
    "Sardegna": "South",
}

PROVINCE_TO_MACROAREA = {
    sigla: REGION_TO_MACROAREA[region]
    for sigla, region in PROVINCE_TO_REGION.items()
    if region in REGION_TO_MACROAREA
}


def macroarea_of(sigla: str) -> Optional[str]:
    """Return 'North', 'Centre', or 'South' for a 2-letter province sigla."""
    return PROVINCE_TO_MACROAREA.get(str(sigla).strip().upper())


ISTAT_PROVINCE_PREFIX_TO_SIGLA = {
    "001": "TO",
    "002": "VC",
    "003": "NO",
    "004": "CN",
    "005": "AT",
    "006": "AL",
    "007": "AO",
    "008": "IM",
    "009": "SV",
    "010": "GE",
    "011": "SP",
    "012": "VA",
    "013": "CO",
    "014": "SO",
    "015": "MI",
    "016": "BG",
    "017": "BS",
    "018": "PV",
    "019": "CR",
    "020": "MN",
    "021": "BZ",
    "022": "TN",
    "023": "VR",
    "024": "VI",
    "025": "BL",
    "026": "TV",
    "027": "VE",
    "028": "PD",
    "029": "RO",
    "030": "UD",
    "031": "GO",
    "032": "TS",
    "033": "PC",
    "034": "PR",
    "035": "RE",
    "036": "MO",
    "037": "BO",
    "038": "FE",
    "039": "RA",
    "040": "FC",
    "041": "PU",
    "042": "AN",
    "043": "MC",
    "044": "AP",
    "045": "MS",
    "046": "LU",
    "047": "PT",
    "048": "FI",
    "049": "LI",
    "050": "PI",
    "051": "AR",
    "052": "SI",
    "053": "GR",
    "054": "PG",
    "055": "TR",
    "056": "VT",
    "057": "RI",
    "058": "RM",
    "059": "LT",
    "060": "FR",
    "061": "CE",
    "062": "BN",
    "063": "NA",
    "064": "AV",
    "065": "SA",
    "066": "AQ",
    "067": "TE",
    "068": "PE",
    "069": "CH",
    "070": "CB",
    "071": "FG",
    "072": "BA",
    "073": "TA",
    "074": "BR",
    "075": "LE",
    "076": "PZ",
    "077": "MT",
    "078": "CS",
    "079": "CZ",
    "080": "RC",
    "081": "TP",
    "082": "PA",
    "083": "ME",
    "084": "AG",
    "085": "CL",
    "086": "EN",
    "087": "CT",
    "088": "RG",
    "089": "SR",
    "090": "SS",
    "091": "NU",
    "092": "CA",
    "093": "PN",
    "094": "IS",
    "095": "OR",
    "096": "BI",
    "097": "LC",
    "098": "LO",
    "099": "RN",
    "100": "PO",
    "101": "KR",
    "102": "VV",
    "103": "VB",
    "108": "MB",
    "109": "FM",
    "110": "BT",
    "111": "SU",
}

NUTS_TO_SIGLA = {
    "IT108": "MB",
    "IT109": "FM",
    "IT110": "BT",
    "IT111": "SU",
    "ITC11": "TO",
    "ITC12": "VC",
    "ITC13": "BI",
    "ITC14": "VB",
    "ITC15": "NO",
    "ITC16": "CN",
    "ITC17": "AT",
    "ITC18": "AL",
    "ITC20": "AO",
    "ITC31": "IM",
    "ITC32": "SV",
    "ITC33": "GE",
    "ITC34": "SP",
    "ITC41": "VA",
    "ITC42": "CO",
    "ITC43": "LC",
    "ITC44": "SO",
    "ITC45": "MI",
    "ITC46": "BG",
    "ITC47": "BS",
    "ITC48": "PV",
    "ITC49": "LO",
    "ITC4A": "CR",
    "ITC4B": "MN",
    "ITC4C": "MI",
    "ITC4D": "MB",
    "ITD10": "BZ",
    "ITD20": "TN",
    "ITD31": "VR",
    "ITD32": "VI",
    "ITD33": "BL",
    "ITD34": "TV",
    "ITD35": "VE",
    "ITD36": "PD",
    "ITD37": "RO",
    "ITD41": "PN",
    "ITD42": "UD",
    "ITD43": "GO",
    "ITD44": "TS",
    "ITD51": "PC",
    "ITD52": "PR",
    "ITD53": "RE",
    "ITD54": "MO",
    "ITD55": "BO",
    "ITD56": "FE",
    "ITD57": "RA",
    "ITD58": "FC",
    "ITD59": "RN",
    "ITE11": "MS",
    "ITE12": "LU",
    "ITE13": "PT",
    "ITE14": "FI",
    "ITE15": "PO",
    "ITE16": "LI",
    "ITE17": "PI",
    "ITE18": "AR",
    "ITE19": "SI",
    "ITE1A": "GR",
    "ITE21": "PG",
    "ITE22": "TR",
    "ITE31": "PU",
    "ITE32": "AN",
    "ITE33": "MC",
    "ITE34": "AP",
    "ITE41": "VT",
    "ITE42": "RI",
    "ITE43": "RM",
    "ITE44": "LT",
    "ITE45": "FR",
    "ITF11": "AQ",
    "ITF12": "TE",
    "ITF13": "PE",
    "ITF14": "CH",
    "ITF21": "IS",
    "ITF22": "CB",
    "ITF31": "CE",
    "ITF32": "BN",
    "ITF33": "NA",
    "ITF34": "AV",
    "ITF35": "SA",
    "ITF41": "FG",
    "ITF42": "BA",
    "ITF43": "TA",
    "ITF44": "BR",
    "ITF45": "LE",
    "ITF46": "FG",
    "ITF47": "BA",
    "ITF48": "BT",
    "ITF51": "PZ",
    "ITF52": "MT",
    "ITF61": "CS",
    "ITF62": "KR",
    "ITF63": "CZ",
    "ITF64": "VV",
    "ITF65": "RC",
    "ITG11": "TP",
    "ITG12": "PA",
    "ITG13": "ME",
    "ITG14": "AG",
    "ITG15": "CL",
    "ITG16": "EN",
    "ITG17": "CT",
    "ITG18": "RG",
    "ITG19": "SR",
    "ITG21": "SS",
    "ITG22": "NU",
    "ITG23": "OR",
    "ITG24": "CA",
    "ITG25": "SS",
    "ITG26": "NU",
    "ITG27": "CA",
    "ITG28": "OR",
    "ITG29": "SS",
    "ITG2A": "OG",
    "ITG2B": "VS",
    "ITG2C": "CI",
    "ITG2D": "SS",
    "ITG2E": "NU",
    "ITG2F": "CA",
    "ITG2G": "OR",
    "ITG2H": "SU",
    "ITH10": "BZ",
    "ITH20": "TN",
    "ITH31": "VR",
    "ITH32": "VI",
    "ITH33": "BL",
    "ITH34": "TV",
    "ITH35": "VE",
    "ITH36": "PD",
    "ITH37": "RO",
    "ITH41": "PN",
    "ITH42": "UD",
    "ITH43": "GO",
    "ITH44": "TS",
    "ITH51": "PC",
    "ITH52": "PR",
    "ITH53": "RE",
    "ITH54": "MO",
    "ITH55": "BO",
    "ITH56": "FE",
    "ITH57": "RA",
    "ITH58": "FC",
    "ITH59": "RN",
    "ITI11": "MS",
    "ITI12": "LU",
    "ITI13": "PT",
    "ITI14": "FI",
    "ITI15": "PO",
    "ITI16": "LI",
    "ITI17": "PI",
    "ITI18": "AR",
    "ITI19": "SI",
    "ITI1A": "GR",
    "ITI21": "PG",
    "ITI22": "TR",
    "ITI31": "PU",
    "ITI32": "AN",
    "ITI33": "MC",
    "ITI34": "AP",
    "ITI35": "FM",
    "ITI41": "VT",
    "ITI42": "RI",
    "ITI43": "RM",
    "ITI44": "LT",
    "ITI45": "FR",
}


def map_area_code_to_sigla(area_code: str) -> Optional[str]:
    """Map any supported area code format to 2-letter province sigla."""
    if area_code is None:
        return None

    code = str(area_code).strip().upper()
    if not code or code in {"NAN", "NONE"}:
        return None

    # Normalize pure numeric ISTAT-like codes that may have lost leading zeros.
    if code.isdigit() and len(code) < 6:
        code = code.zfill(6)

    if code in PROVINCE_TO_REGION:
        return code

    if code.startswith("IT-") and len(code) == 5:
        candidate = code[-2:]
        if candidate in PROVINCE_TO_REGION:
            return candidate

    if code in NUTS_TO_SIGLA:
        return NUTS_TO_SIGLA[code]

    # Legacy mixed format IT + 3-digit ISTAT province code.
    m = re.fullmatch(r"IT(\d{3})", code)
    if m:
        return ISTAT_PROVINCE_PREFIX_TO_SIGLA.get(m.group(1))

    # Municipal code: 3-digit province prefix + 3-digit municipality id.
    m = re.fullmatch(r"(\d{6})", code)
    if m:
        return ISTAT_PROVINCE_PREFIX_TO_SIGLA.get(code[:3])

    return None
